@echo off
echo Activating virtual environment...
call .\venv\Scripts\activate

echo Updating & Upgrading setup libraries...
pip install --upgrade pip setuptools wheel

echo Installing dependencies...
pip install -r requirements.txt


echo Press any key to exit...
pause >nul
